### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by mrflix** [johannschopplich/kirby-vue3-starterkit#5] opened 2020-10-02 12:53 UTC
I'll be looking into multi-language support and was wondering if you already looked into it a bit yourself? If I find a good solution I'd be willing to contribute it to the core.

**Comment by johannschopplich** [comment] 2020-10-02 21:03
Sounds wondeful! I haven't thought about multi language support in depth. I guess part of the logic might be adaptable from https://github.com/jmheretik/kirby-vue-starterkit/issues/5#issuecomment-616108239, but updated for the setup of this repository. After all it should be that complicated. But I don't want to go out on a limb. 😉 

I'm interested in your approach!

**Comment by mrflix** [comment] 2020-10-03 17:40
Thanks for the pointer! That's very helpful for the start :)

**Comment by johannschopplich** [comment] 2020-10-26 09:30
Hey @mrflix, I've created a new branch with preliminary multi-lang support: https://github.com/johannschopplich/kirby-vue3-starterkit/compare/multi-lang-support. It works without any languages set (default) as well as it should work with custom languages defined in the `config.php`. 
You're welcome to test and modify! I haven't tested extensively. Also I'm not sure if I want to merge it to the core, as it may complicates the already complex setup for newcomers to this starterkit. Will leave in in a seperate branch for now. 

Credits to @jmheretik for his endeavours around multi-language support!

**Comment by getflourish** [comment] 2020-12-08 08:50
Looking forward to this! Tried to run it but I’m getting some errors that I’ll try to fix:

```
[1] [vite] SFC <script setup> compilation error:
[1] .../kirby-vue3-starterkit-multi-lang-support/frontend/src/components/Footer.vue
[1] [@vue/compiler-sfc] <script setup> cannot contain ES module exports. If you are using a previous version of <script setup>, please consult the updated RFC at https://github.com/vuejs/rfcs/pull/227.
[1] 
[1] .../kirby-vue3-starterkit-multi-lang-support/frontend/src/components/Footer.vue
[1] 19 |  <script setup>
[1] 20 |  import { useSite } from '../hooks'
[1] 21 |  
[1]    |   ^
[1] 22 |  export const site = useSite()
[1]    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1] 23 |  </script>
```

**Comment by johannschopplich** [comment] 2020-12-08 10:18
@getflourish Yeah, the `<script setup>` RFC keeps changing. I reverted to plain `<script>` upstream already and will soon push the same changes to the multi-language branch. 

Your second error message has been fixed as well. Thanks for reporting!

**Comment by johannschopplich** [comment] 2020-12-08 10:52
@mrflix @getflourish I've updated the [multi-lang branch](https://github.com/johannschopplich/kirby-vue3-starterkit/tree/multi-lang-support) to include changes made upstream as well as fixed some minor issues.

You may now test again. 🙂 Be sure to enable languages in the Kirby config and add testing content. Looking forward to your feedback.

**Comment by getflourish** [comment] 2020-12-08 17:05
Looking better now. Next I need to figure out how to upgrade PHP on macOS :D

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.11.`

Will keep you posted :) Thanks!

**Comment by getflourish** [comment] 2020-12-08 17:42
Okay, upgraded PHP and now it works!

**Comment by johannschopplich** [comment] 2020-12-08 17:43
I was just about to write a little manual. 😉  Wonderful to hear!

**Comment by getflourish** [comment] 2020-12-09 14:27
Correct me if I’m wrong, but does this setup assume content to be in language-specific folders? The API request in my test with two languages enabled looks like this:

```
[Log] [useLanguages] Current language code – "de" (useLanguages.js, line 27)
[Log] [getPage] Fetching /content/de/test.json… (useKirbyApi.js, line 71)
```

But doesn’t Kirby / the Panel use a different system?

```
content/about/test.de.txt
content/about/test.en.txt
```

If the content is stored like that (the Kirby way), it doesn’t seem to work. Only if I create a ```de``` folder and move the page there, it works.

**Comment by johannschopplich** [comment] 2020-12-09 14:40
No, Kirby's folder setup stays the same. Otherwise the panel wouldn't work. I try to introduce as few changes to the standard processes of Kirby as possible.

The slug `content` might be misleading; is has nothing to do with the actual content folder of Kirby. You can define a custom content api slug, which will be used to fetch the JSON files. You can define it in your [`.env`](https://github.com/johannschopplich/kirby-vue3-starterkit/blob/master/.env.example#L8). It can even be empty, thus request URLs will be similar to URLs built by e.g. `$page->url()`, just with a `.json` suffix.

Also this project uses the `public` folder as main entry point for web servers. No content from `content` is accessible. I like this folder setup more than the default Kirby setup for security reasons. It's also visually more appealing... But I digress.

Each JSON requested is [intercepted by a custom route](https://github.com/johannschopplich/kirby-vue3-starterkit/blob/master/site/plugins/kirby-spa-adapter/routes.php). Calling a JSON file just returns the template, which would normally contain HTML instead of JSON.

Your `/content/de/test.json` would be `/content/test.json` in a non-multi language setup. Or even just `/test.json` if the content api slug is left empty.

I have to recreate a local multi-lang site for testing purposes. Then I will look into it.

**Comment by johannschopplich** [comment] 2020-12-09 15:56
@getflourish Fixed with https://github.com/johannschopplich/kirby-vue3-starterkit/commit/9cd741ed3fb624d92cef7e10e6a59924434027a2. The actual content of multi-language sites wasn't returned properly. I've also improved the DX by prioritizing the language based on the user's browser.

**Comment by getflourish** [comment] 2020-12-09 16:33
Thank you so much for looking into this!

I was already starting to look into `routes.php` but couldn’t figure out what’s going on :D

I’ve downloaded the fixed version, but it’s not working for me :(

`localhost:3000/de/about`
`localhost:3000/en/about`

=> Error page

`Fetching /spa/de/de/about.json…`
`Fetching /spa/de/en/about.json…`

What works is the base URL without language:

`http://localhost:3000/about`

=>

` /spa/de/about.json…`

FYI: I’ve enabled languages in the config and then set up the languages through the panel…

**Comment by getflourish** [comment] 2020-12-09 16:45
Ah, this is interesting:

[Log] [useLanguages] Current language code: – "de" (useLanguages.js, line 26)
[Log] [getPage] Fetching /spa/de/en/about.json… (useKirbyApi.js, line 71)

Language code gets detected as `de` (browser / system), which conflicts with the attempt to get a different language version by using `/en` in the URL…

**Comment by johannschopplich** [comment] 2020-12-09 16:59
The `base` of the router was undefined, therefore the URL prefix missing. Fixed in https://github.com/johannschopplich/kirby-vue3-starterkit/commit/44286f0c88555664959b94ba2577c40bc1d4b3f7.

**Comment by getflourish** [comment] 2020-12-09 17:44
Didn’t do the trick for me, but I’m getting there:

I was wondering wether the language code should stem from the URL instead of `navigator.language`?

I’ve hacked this one in `useLanguages.js` and it does what I’m expecting. I haven’t tested it without language setup though :)

// Grab the language code from the URL
languageCode = site.languages.find(lang => window.location.pathname.startsWith(`/${lang.code}`))?.code

Only thing missing for me now is that the `useSite` seems to always return the data from the default language which means that, e.g. in the navigation I always see the default language. Will look into `routes.php`, `useSite.js` :D

**Comment by johannschopplich** [comment] 2020-12-09 17:53
Right, should be the location instead of the browser's language. Fixed in https://github.com/johannschopplich/kirby-vue3-starterkit/commit/4703a28b593549e1f0bf7ed5e8924d30413f49e8.

Regarding site: be my guests. You will have to edit [`site/config/spa-site.php`](https://github.com/johannschopplich/kirby-vue3-starterkit/blob/multi-lang-support/site/config/spa-site.php).

**Comment by johannschopplich** [comment] 2020-12-09 19:42
@getflourish Haven't tested, but should work just fine. https://github.com/johannschopplich/kirby-vue3-starterkit/commit/1fb7ffa7880f34fa7839e745ed8810b32516784c

`kirby()->languageCode()` returns either the current language's code or `null`. Can be passed to the `$page->content()` function to return the field for a given language.

**Comment by johannschopplich** [comment] 2020-12-09 22:00
@getflourish Well, it took some time, but I got the setup working for the development environment as well. That was the hard part. See https://github.com/johannschopplich/kirby-vue3-starterkit/commit/e688451d03440633c0f233ef9e384945048bc0bc.

Only thing left as far as I can see: opening `localhost:3000` doesn't work and won't redirect. You will have to call `localhost:3000/en/` directly for example. Of course in production Kirby redirects any visits of the root path to the appropriate language code.

**Comment by getflourish** [comment] 2020-12-10 08:20
🙏 Omg thank you!

Okay, after a quick test I can confirm it’s working on `prod` when using 127.0.0.1, content is translated on `dev`, too, but the site-specific stuff on dev always shows the default language.

I tried so much yesterday and became a bit frustrated because I didn’t know where to start: at some point I had it working on the frontend but Kirby basically didn’t know about it (so quite the opposite of what I’m seeing now ^^)

One thing I noticed when setting it up was that I was going to set up languages in the panel which didn’t work because `routes.php` expects languages to be passed which didn’t exist. I took the manual path then to set them up. But doesn’t matter right now for testing. 

<img width="1552" alt="Screenshot 2020-12-10 at 09 14 26" src="https://user-images.githubusercontent.com/183989/101739701-33b06300-3ac8-11eb-9a6e-e1e547da9cf6.png">

So: Just wondering why site-specific translations (e.g. navigation) don’t work in dev. If they do work in prod that’s already good enough.

This is a beast 🥶

**Comment by johannschopplich** [comment] 2020-12-10 09:28
Oh no, it shouldn't be frustrating. 

It's a beast indeed. Mainly because I want the multi-lang setup to be optional, a reasonable implementation and everything working as well in single-language mode. And of course best DX for the developer. I've fixed the bug you described just now. Please fetch the latest changes.

You've done everything right setting up the languages in the panel. I've just fixed fetching the correct `site` object in development environment. 🎉 

Thanks for your continuous bug hunting!

**Comment by getflourish** [comment] 2020-12-10 11:19
🎉🎉🎉 It works! 

I will try to test it more extensively and see if I run into edge cases.

Thanks you so much!

**Comment by getflourish** [comment] 2020-12-10 11:26
Two things that already come to my mind:

Does this setting in the `config` still have an effect? I don’t think so?

```
'languages.detect' => true
```

And inside a `languages/en.php`, setting custom url’s won’t work as far as I can tell:

```
'url' => NULL
```

```
<?php

return [
    'code' => 'en',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'en_US'
    ],
    'name' => 'English',
    'translations' => [

    ],
    'url' => 'english'
];
```

But this is not relevant for me right now. Just something to consider.

**Comment by johannschopplich** [comment] 2020-12-10 13:31
Language detection works in production, since it's handled by Kirby itself! 💯 It would be implementable in development as well, but I don't want to introduce more complexity. I trust the developer can visit the language he want to test locally. Of course I'm open for arguments for the implementation.

I've worked on custom language paths locally, but then the complexity increased again and there are again more edge-cases to consider. For the moment I'm sticking with only language codes. I'll add a note about that limitation in the README. I haven't seen custom language slugs on websites at all. Therefore I don't want to increase complexity for this niche feature. Again: open for arguments. 😉 
Custom URL aren't editable via the panel anyway.

**Closed** 2020-12-11 07:39 UTC
